breed_descriptions = {
    "Alambadi": "Alambadi is a traditional draught breed from Tamil Nadu, almost extinct today. Once used in Raekla racing, farmers complain its decline is due to banning of cultural sports and crossbreeding with exotic cows.",
    "Amrit Mahal": "Amrit Mahal is a draught breed from Karnataka, developed from Hallikar and related breeds. Known for endurance and speed, it was once used in war transport. Cows yield little milk, so it is classified as a draught breed.",
    "Ayrshire": "Ayrshire is a dairy cattle breed from Scotland, named after Ayrshire county. They are red and white in color and produce high-quality milk.",
    "Banni": "Banni buffalo, also called Kutchi or Kundi, originates in Gujarat’s Kutch district. Known for resilience in arid conditions, they yield 12–18 litres of milk daily and are raised by the Maldhari community.",
    "Bargur": "Bargur cattle from Tamil Nadu are medium-sized, aggressive, and adapted to hilly forests. They have great endurance, trotting ability, and their milk is believed to have medicinal value.",
    "Bhadwari": "Bhadwari is a buffalo breed from Uttar Pradesh and Madhya Pradesh, known for high milk yield with good fat content. They lactate for ~272 days producing 750–800 kg of milk.",
    "Brown Swiss": "Brown Swiss is a dairy cattle breed from the Alpine region, now bred mainly in the U.S. Known for high milk yield (~10,000 kg/year) with 4% butterfat, ideal for cheese-making.",
    "Dangi": "Dangi cattle originate from Maharashtra, well adapted to heavy rainfall and hilly tracts. Their skin secretes oil, protecting them in wet climates. They are strong draught animals.",
    "Deoni": "Deoni is a draught breed from Maharashtra and parts of Karnataka. Named after Deoni taluk, it is valued for strength in agriculture and fair milk production.",
    "Gir": "Gir, from Gujarat’s Kathiawar peninsula, is a famous dairy breed. Exported worldwide, especially to Brazil, it forms the base of many dairy crossbreeds.",
    "Guernsey": "Guernsey is a dairy breed from the Channel Islands. Known for docility, it produces rich, golden-yellow milk high in beta-carotene and butterfat.",
    "Hallikar": "Hallikar is a traditional draught breed from Karnataka, famous for stamina and strength, often used in bullock cart races.",
    "Hariana": "Hariana is a dual-purpose cattle breed from Haryana. Pure Harianas yield 10–15 litres/day, while crossbreeding improves yield but reduces disease resistance.",
    "Holstein Friesian": "Holstein Friesians are the world’s dominant dairy cattle, originating in northern Europe. Recognizable by black-and-white coat, they produce the highest milk yields globally.",
    "Jafarabadi": "Jafarabadi buffalo from Gujarat is one of India’s heaviest buffalo breeds. Exported to Brazil, it is valued for both milk and meat.",
    "Jersey": "Jersey cattle from the Channel Islands are small dairy cows producing milk rich in butterfat, with a golden-yellow tinge.",
    "Kangayam": "Kangayam cattle from Tamil Nadu are hardy draught animals, strong and disease-resistant, often used in ploughing.",
    "Kankrej": "Kankrej is a dual-purpose cattle breed from Gujarat and Rajasthan, used both for milk and draught work. Known for disease resistance and adaptability.",
    "Kasaragod Dwarf": "Kasaragod Dwarf from Kerala is a small, hardy breed giving nutrient-rich milk. They are intelligent, require minimal inputs, and are excellent for free-range rearing.",
    "Kenkatha": "Kenkatha, or Kenwariya, is a small draught breed from Uttar Pradesh and Madhya Pradesh, adapted to poor forage and harsh conditions.",
    "Kherigarh": "Kherigarh from Uttar Pradesh is mainly used for light draught work. Closely related to Malwa cattle.",
    "Khillari": "Khillari cattle are hardy draught animals from Maharashtra and Karnataka, adapted to drought-prone areas.",
    "Krishna Valley": "Krishna Valley breed from Karnataka and Maharashtra was developed in the 19th century as strong draught animals for agriculture.",
    "Malnad Gidda": "Malnad Gidda is a dwarf cattle breed from Karnataka’s Western Ghats. Known for disease resistance, adaptability, and medicinal milk/urine.",
    "Mehsana": "Mehsana buffalo from Gujarat is a Murrah–Surti cross, one of India’s best dairy buffalo breeds with high milk yield.",
    "Murrah": "Murrah buffalo from Haryana and Punjab is India’s most famous dairy buffalo. They produce very high milk yields and are exported worldwide.",
    "Nagori": "Nagori cattle from Rajasthan are a draught breed, used for ploughing and cart pulling, originating in Nagaur district.",
    "Nagpuri": "Nagpuri buffalo from Maharashtra is a dual-purpose river buffalo, well suited for both milk and draught work.",
    "Nili-Ravi": "Nili-Ravi is a major buffalo breed from Punjab (India & Pakistan). Known for high milk yield, it resembles Murrah but is larger and robust.",
    "Nimari": "Nimari cattle from Madhya Pradesh and Maharashtra are medium to large, draught animals, with red coloration and Gir–Khillari ancestry.",
    "Ongole": "Ongole cattle from Andhra Pradesh are strong draught animals, resistant to many diseases. They are famous for use in bullfights abroad.",
    "Pulikulam": "Pulikulam cattle from Tamil Nadu are small zebu cattle used in Jallikattu. They are hardy, aggressive, and locally adapted.",
    "Rathi": "Rathi cattle from Rajasthan are a dairy breed of the Thar Desert. Managed by nomadic Rath people, they yield good milk even in arid conditions.",
    "Red Sindhi": "Red Sindhi from Sindh (Pakistan) is a dairy breed, well adapted to hot climates. Widely used in crossbreeding programs for tropical dairy farming.",
    "Surti": "Surti buffalo from Gujarat has sickle-shaped horns. Known for good milk yield (1600–1800 litres) with 8–10% fat content.",
    "Tharparkar": "Tharparkar cattle from Rajasthan and Sindh are dual-purpose, adapted to arid climates, producing both milk and draught power.",
    "Toda": "Toda buffalo from Tamil Nadu’s Nilgiris are sacred to the Toda tribe. Used in rituals, they produce milk with high fat content.",
    "Umblachery": "Umblachery cattle from Tamil Nadu are small draught animals, mainly used in paddy fields.",
    "Vechur": "Vechur cattle from Kerala are the world’s smallest cattle breed. Despite their size, they produce proportionally high-quality milk.",
}
